# .github/workflows/main.yml

name: Simple Test Pipeline

on:
  push:
    branches: [CICD]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Quellcode auschecken
        uses: actions/checkout@v4

      - name: Einfacher Testschritt
        run: echo "Workflow läuft erfolgreich!"
