name: Pipeline with ServiceNow Change Control

on:
  push:
    branches:
      - CICD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Quellcode auschecken
        uses: actions/checkout@v4
      - name: Einfacher Build Schritt
        run: echo "Build erfolgreich!"

  ServiceNowDevOpsChange:
        # jobs that must complete successfully before this job will run
        needs: build
        # type of machine to run the job on
        runs-on: ubuntu-latest
        name: 'ServiceNow DevOps Change'
        steps:
          - name: ServiceNow Change
            # Ensure to update to the latest version of the custom action, for e.g. ServiceNow/servicenow-devops-change@v5.1.0
            uses: ServiceNow/servicenow-devops-change@v5.1.0
            with:
              # Devops Integration Tokens
              devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
              # ServiceNow Instance URL
              instance-url: ${{ secrets.SN_INSTANCE_URL }}
              # Orchestration Tool Id
              tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
              # GitHub Context
              context-github: ${{ toJSON(github) }}
              # Display Name of the Job
              job-name: 'ServiceNow DevOps Change'



